workflows:
  android-release:
    name: Build Vidyakunj Attendance Android APK
    environment:
      node: 22.0.0
      vars:
        PACKAGE_NAME: "com.vidyakunj.attendance"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
