workflows:
  build_web:
    name: Build Vidyakunj Flutter Web App
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - flutter config --enable-web
      - flutter pub get
      - flutter build web --release
    artifacts:
      - build/web/**
