workflows:
  flutter-web-build:
    name: Build Vidyakunj Flutter Web App
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build Flutter Web
        script: |
          flutter build web
    artifacts:
      - build/web/**
    publishing:
      web:
        folder: build/web
