workflows:
  build_android:
    name: Build Vidyakunj Android APK
    max_build_duration: 120
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

    environment:
      flutter: stable
      java: openjdk17

    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
